// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;





class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS. '
              'Run FlutterFire CLI to generate options.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows. '
              'Run FlutterFire CLI to generate options.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux. '
              'Run FlutterFire CLI to generate options.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW87iQNY_LR-0usixm9yPbv4Cl7FbUxrU',
    appId: '1:79272043513:web:707801807b97d5b55a5328',
    messagingSenderId: '79272043513',
    projectId: 'medicine-reminder-3cb0c',
    storageBucket: 'medicine-reminder-3cb0c.firebasestorage.app',
  );


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF-3vhMDaQ2Cos9j56Nj68sPb6lN6s2S0',
    appId: '1:79272043513:android:4e9a4f3c60554dcc5a5328',
    messagingSenderId: '79272043513',
    projectId: 'medicine-reminder-3cb0c',
    storageBucket: 'medicine-reminder-3cb0c.firebasestorage.app',
  );


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjZInJxtZN55_y4O1l4tFPNvGm-mdC4y4',
    appId: '1:237911679905:ios:728d881851a7cfac8d21e0',
    messagingSenderId: '237911679905',
    projectId: 'medicine-reminder-a898d',
    storageBucket: 'medicine-reminder-a898d.firebasestorage.app',
    iosBundleId: 'com.example.medicineReminder',
  );
}
